<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPk6KxWs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPk6KxWs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPk6KxWs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPk6KxWs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPk6KxWs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pk6KxWs',
    'container.build_id' => 'e52b8a0e',
    'container.build_time' => 1578067763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPk6KxWs');
